name: quickleez
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  flutter_settings_ui:
  device_preview:
  flutter_screenutil: 
  flutter_animate:
  curved_navigation_bar:
  cupertino_icons:
  flutter_svg:
  carousel_slider: 
  smooth_page_indicator:
  http:
  shared_preferences:
  google_sign_in:
  flutter_local_notifications:
  intl:
  lottie:
  animations:
  provider:
  url_launcher:
  share_plus:
  image_picker: 
  emoji_picker_flutter: 
  iconsax: 
  firebase_core: 
  firebase_storage:
  cloud_firestore:
  shimmer:
  video_player:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints:





flutter:
  uses-material-design: true
  assets:
    - assets/logo/quickleez.png
    - assets/logo/quickleez_1.png
    - assets/logo/ql.png
    - assets/88.webm
